// <auto-generated />
using System;
using ArtiX.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ArtiX.Infrastructure.Migrations
{
    [DbContext(typeof(ErpDbContext))]
    [Migration("20251207120000_AddProductTaxInclusiveFlag")]
    partial class AddProductTaxInclusiveFlag
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
            // This migration relies on the existing snapshot for full model details.
        }
    }
}
