// <auto-generated />
#nullable disable
using System;
using ArtiX.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;

namespace ArtiX.Infrastructure.Migrations
{
    [DbContext(typeof(ErpDbContext))]
    partial class ErpDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0");

            modelBuilder.Entity("ArtiX.Domain.Entities.Core.Account", b =>
            {
                b.Property<Guid>("Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("uniqueidentifier");

                b.Property<Guid?>("BranchId")
                    .HasColumnType("uniqueidentifier");

                b.Property<Guid>("CompanyId")
                    .HasColumnType("uniqueidentifier");

                b.Property<DateTime>("CreatedAt")
                    .HasColumnType("datetime2");

                b.Property<Guid?>("TenantId")
                    .HasColumnType("uniqueidentifier");

                b.Property<DateTime?>("UpdatedAt")
                    .HasColumnType("datetime2");

                b.HasKey("Id");

                b.HasIndex("CompanyId");

                b.ToTable("Accounts");
            });

            modelBuilder.Entity("ArtiX.Domain.Entities.Core.Branch", b =>
            {
                b.Property<Guid>("Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("uniqueidentifier");

                b.Property<Guid?>("BranchId")
                    .HasColumnType("uniqueidentifier");

                b.Property<int>("BranchType")
                    .HasColumnType("int");

                b.Property<Guid>("CompanyId")
                    .HasColumnType("uniqueidentifier");

                b.Property<DateTime>("CreatedAt")
                    .HasColumnType("datetime2");

                b.Property<string>("Name")
                    .IsRequired()
                    .HasColumnType("nvarchar(max)");

                b.Property<Guid?>("TenantId")
                    .HasColumnType("uniqueidentifier");

                b.Property<DateTime?>("UpdatedAt")
                    .HasColumnType("datetime2");

                b.Property<string>("Code")
                    .IsRequired()
                    .HasColumnType("nvarchar(max)");

                b.HasKey("Id");

                b.HasIndex("CompanyId");

                b.ToTable("Branches");
            });

            modelBuilder.Entity("ArtiX.Domain.Entities.Core.Company", b =>
            {
                b.Property<Guid>("Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("uniqueidentifier");

                b.Property<Guid?>("BranchId")
                    .HasColumnType("uniqueidentifier");

                b.Property<string>("Code")
                    .IsRequired()
                    .HasColumnType("nvarchar(max)");

                b.Property<Guid?>("CompanyId")
                    .HasColumnType("uniqueidentifier");

                b.Property<DateTime>("CreatedAt")
                    .HasColumnType("datetime2");

                b.Property<string>("Name")
                    .IsRequired()
                    .HasColumnType("nvarchar(max)");

                b.Property<string>("TaxNumber")
                    .HasColumnType("nvarchar(max)");

                b.Property<Guid?>("TenantId")
                    .HasColumnType("uniqueidentifier");

                b.Property<DateTime?>("UpdatedAt")
                    .HasColumnType("datetime2");

                b.HasKey("Id");

                b.ToTable("Companies");
            });

            modelBuilder.Entity("ArtiX.Domain.Entities.Core.Customer", b =>
            {
                b.Property<Guid>("Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("uniqueidentifier");

                b.Property<Guid?>("BranchId")
                    .HasColumnType("uniqueidentifier");

                b.Property<Guid>("CompanyId")
                    .HasColumnType("uniqueidentifier");

                b.Property<DateTime>("CreatedAt")
                    .HasColumnType("datetime2");

                b.Property<Guid?>("DefaultSalesRepresentativeId")
                    .HasColumnType("uniqueidentifier");

                b.Property<Guid?>("TenantId")
                    .HasColumnType("uniqueidentifier");

                b.Property<DateTime?>("UpdatedAt")
                    .HasColumnType("datetime2");

                b.HasKey("Id");

                b.HasIndex("BranchId");

                b.HasIndex("CompanyId");

                b.HasIndex("DefaultSalesRepresentativeId");

                b.ToTable("Customers");
            });

            modelBuilder.Entity("ArtiX.Domain.Entities.Core.Product", b =>
            {
                b.Property<Guid>("Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("uniqueidentifier");

                b.Property<Guid?>("BranchId")
                    .HasColumnType("uniqueidentifier");

                b.Property<Guid>("CompanyId")
                    .HasColumnType("uniqueidentifier");

                b.Property<DateTime>("CreatedAt")
                    .HasColumnType("datetime2");

                b.Property<Guid?>("TenantId")
                    .HasColumnType("uniqueidentifier");

                b.Property<DateTime?>("UpdatedAt")
                    .HasColumnType("datetime2");

                b.HasKey("Id");

                b.HasIndex("CompanyId");

                b.ToTable("Products");
            });

            modelBuilder.Entity("ArtiX.Domain.Entities.Core.SalesChannel", b =>
            {
                b.Property<Guid>("Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("uniqueidentifier");

                b.Property<Guid?>("BranchId")
                    .HasColumnType("uniqueidentifier");

                b.Property<int>("ChannelType")
                    .HasColumnType("int");

                b.Property<string>("Code")
                    .IsRequired()
                    .HasColumnType("nvarchar(max)");

                b.Property<Guid>("CompanyId")
                    .HasColumnType("uniqueidentifier");

                b.Property<DateTime>("CreatedAt")
                    .HasColumnType("datetime2");

                b.Property<string>("ExternalSystem")
                    .HasColumnType("nvarchar(max)");

                b.Property<bool>("IsActive")
                    .HasColumnType("bit");

                b.Property<bool>("IsOnline")
                    .HasColumnType("bit");

                b.Property<string>("Name")
                    .IsRequired()
                    .HasColumnType("nvarchar(max)");

                b.Property<Guid?>("TenantId")
                    .HasColumnType("uniqueidentifier");

                b.Property<DateTime?>("UpdatedAt")
                    .HasColumnType("datetime2");

                b.HasKey("Id");

                b.HasIndex("CompanyId");

                b.ToTable("SalesChannels");
            });

            modelBuilder.Entity("ArtiX.Domain.Entities.Core.SalesRepresentative", b =>
            {
                b.Property<Guid>("Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("uniqueidentifier");

                b.Property<Guid?>("BranchId")
                    .HasColumnType("uniqueidentifier");

                b.Property<Guid>("CompanyId")
                    .HasColumnType("uniqueidentifier");

                b.Property<DateTime>("CreatedAt")
                    .HasColumnType("datetime2");

                b.Property<string>("Email")
                    .HasColumnType("nvarchar(max)");

                b.Property<string>("FullName")
                    .IsRequired()
                    .HasColumnType("nvarchar(max)");

                b.Property<string>("Phone")
                    .HasColumnType("nvarchar(max)");

                b.Property<Guid?>("TenantId")
                    .HasColumnType("uniqueidentifier");

                b.Property<DateTime?>("UpdatedAt")
                    .HasColumnType("datetime2");

                b.Property<Guid?>("UserId")
                    .HasColumnType("uniqueidentifier");

                b.HasKey("Id");

                b.HasIndex("CompanyId");

                b.ToTable("SalesRepresentatives");
            });

            modelBuilder.Entity("ArtiX.Domain.Entities.Core.Tenant", b =>
            {
                b.Property<Guid>("Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("uniqueidentifier");

                b.Property<Guid?>("BranchId")
                    .HasColumnType("uniqueidentifier");

                b.Property<string>("Code")
                    .HasColumnType("nvarchar(max)");

                b.Property<Guid?>("CompanyId")
                    .HasColumnType("uniqueidentifier");

                b.Property<DateTime>("CreatedAt")
                    .HasColumnType("datetime2");

                b.Property<string>("Name")
                    .IsRequired()
                    .HasColumnType("nvarchar(max)");

                b.Property<Guid?>("TenantId")
                    .HasColumnType("uniqueidentifier");

                b.Property<DateTime?>("UpdatedAt")
                    .HasColumnType("datetime2");

                b.HasKey("Id");

                b.ToTable("Tenants");
            });

            modelBuilder.Entity("ArtiX.Domain.Entities.Core.Warehouse", b =>
            {
                b.Property<Guid>("Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("uniqueidentifier");

                b.Property<Guid?>("BranchId")
                    .HasColumnType("uniqueidentifier");

                b.Property<Guid>("CompanyId")
                    .HasColumnType("uniqueidentifier");

                b.Property<DateTime>("CreatedAt")
                    .HasColumnType("datetime2");

                b.Property<Guid?>("TenantId")
                    .HasColumnType("uniqueidentifier");

                b.Property<DateTime?>("UpdatedAt")
                    .HasColumnType("datetime2");

                b.HasKey("Id");

                b.HasIndex("BranchId");

                b.HasIndex("CompanyId");

                b.ToTable("Warehouses");
            });

            modelBuilder.Entity("ArtiX.Domain.Entities.Sales.DeliveryNote", b =>
            {
                b.Property<Guid>("Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("uniqueidentifier");

                b.Property<Guid?>("BranchId")
                    .HasColumnType("uniqueidentifier");

                b.Property<Guid>("CompanyId")
                    .HasColumnType("uniqueidentifier");

                b.Property<DateTime>("CreatedAt")
                    .HasColumnType("datetime2");

                b.Property<Guid?>("SalesChannelId")
                    .HasColumnType("uniqueidentifier");

                b.Property<Guid?>("SalesRepresentativeId")
                    .HasColumnType("uniqueidentifier");

                b.Property<Guid?>("TenantId")
                    .HasColumnType("uniqueidentifier");

                b.Property<DateTime?>("UpdatedAt")
                    .HasColumnType("datetime2");

                b.HasKey("Id");

                b.HasIndex("BranchId");

                b.HasIndex("CompanyId");

                b.HasIndex("SalesChannelId");

                b.HasIndex("SalesRepresentativeId");

                b.ToTable("DeliveryNotes");
            });

            modelBuilder.Entity("ArtiX.Domain.Entities.Sales.Invoice", b =>
            {
                b.Property<Guid>("Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("uniqueidentifier");

                b.Property<Guid?>("BranchId")
                    .HasColumnType("uniqueidentifier");

                b.Property<Guid>("CompanyId")
                    .HasColumnType("uniqueidentifier");

                b.Property<DateTime>("CreatedAt")
                    .HasColumnType("datetime2");

                b.Property<Guid?>("SalesChannelId")
                    .HasColumnType("uniqueidentifier");

                b.Property<Guid?>("SalesRepresentativeId")
                    .HasColumnType("uniqueidentifier");

                b.Property<Guid?>("TenantId")
                    .HasColumnType("uniqueidentifier");

                b.Property<DateTime?>("UpdatedAt")
                    .HasColumnType("datetime2");

                b.HasKey("Id");

                b.HasIndex("BranchId");

                b.HasIndex("CompanyId");

                b.HasIndex("SalesChannelId");

                b.HasIndex("SalesRepresentativeId");

                b.ToTable("Invoices");
            });

            modelBuilder.Entity("ArtiX.Domain.Entities.Sales.Payment", b =>
            {
                b.Property<Guid>("Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("uniqueidentifier");

                b.Property<Guid?>("BranchId")
                    .HasColumnType("uniqueidentifier");

                b.Property<Guid>("CompanyId")
                    .HasColumnType("uniqueidentifier");

                b.Property<DateTime>("CreatedAt")
                    .HasColumnType("datetime2");

                b.Property<Guid?>("SalesChannelId")
                    .HasColumnType("uniqueidentifier");

                b.Property<Guid?>("SalesRepresentativeId")
                    .HasColumnType("uniqueidentifier");

                b.Property<Guid?>("TenantId")
                    .HasColumnType("uniqueidentifier");

                b.Property<DateTime?>("UpdatedAt")
                    .HasColumnType("datetime2");

                b.HasKey("Id");

                b.HasIndex("BranchId");

                b.HasIndex("CompanyId");

                b.HasIndex("SalesChannelId");

                b.HasIndex("SalesRepresentativeId");

                b.ToTable("Payments");
            });

            modelBuilder.Entity("ArtiX.Domain.Entities.Sales.Quotation", b =>
            {
                b.Property<Guid>("Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("uniqueidentifier");

                b.Property<Guid?>("BranchId")
                    .HasColumnType("uniqueidentifier");

                b.Property<Guid>("CompanyId")
                    .HasColumnType("uniqueidentifier");

                b.Property<DateTime>("CreatedAt")
                    .HasColumnType("datetime2");

                b.Property<Guid?>("SalesChannelId")
                    .HasColumnType("uniqueidentifier");

                b.Property<Guid?>("SalesRepresentativeId")
                    .HasColumnType("uniqueidentifier");

                b.Property<Guid?>("TenantId")
                    .HasColumnType("uniqueidentifier");

                b.Property<DateTime?>("UpdatedAt")
                    .HasColumnType("datetime2");

                b.HasKey("Id");

                b.HasIndex("BranchId");

                b.HasIndex("CompanyId");

                b.HasIndex("SalesChannelId");

                b.HasIndex("SalesRepresentativeId");

                b.ToTable("Quotations");
            });

            modelBuilder.Entity("ArtiX.Domain.Entities.Sales.SalesOrder", b =>
            {
                b.Property<Guid>("Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("uniqueidentifier");

                b.Property<Guid?>("BranchId")
                    .HasColumnType("uniqueidentifier");

                b.Property<Guid>("CompanyId")
                    .HasColumnType("uniqueidentifier");

                b.Property<DateTime>("CreatedAt")
                    .HasColumnType("datetime2");

                b.Property<Guid?>("SalesChannelId")
                    .HasColumnType("uniqueidentifier");

                b.Property<Guid?>("SalesRepresentativeId")
                    .HasColumnType("uniqueidentifier");

                b.Property<Guid?>("TenantId")
                    .HasColumnType("uniqueidentifier");

                b.Property<DateTime?>("UpdatedAt")
                    .HasColumnType("datetime2");

                b.HasKey("Id");

                b.HasIndex("BranchId");

                b.HasIndex("CompanyId");

                b.HasIndex("SalesChannelId");

                b.HasIndex("SalesRepresentativeId");

                b.ToTable("SalesOrders");
            });

            modelBuilder.Entity("ArtiX.Domain.Entities.Sales.SalesOrderLine", b =>
            {
                b.Property<Guid>("Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("uniqueidentifier");

                b.Property<Guid?>("BranchId")
                    .HasColumnType("uniqueidentifier");

                b.Property<Guid?>("CompanyId")
                    .HasColumnType("uniqueidentifier");

                b.Property<DateTime>("CreatedAt")
                    .HasColumnType("datetime2");

                b.Property<Guid>("ProductId")
                    .HasColumnType("uniqueidentifier");

                b.Property<Guid>("SalesOrderId")
                    .HasColumnType("uniqueidentifier");

                b.Property<Guid?>("TenantId")
                    .HasColumnType("uniqueidentifier");

                b.Property<DateTime?>("UpdatedAt")
                    .HasColumnType("datetime2");

                b.Property<int>("Quantity")
                    .HasColumnType("int");

                b.Property<decimal>("UnitPrice")
                    .HasColumnType("decimal(18,2)");

                b.HasKey("Id");

                b.HasIndex("ProductId");

                b.HasIndex("SalesOrderId");

                b.ToTable("SalesOrderLines");
            });

            modelBuilder.Entity("ArtiX.Domain.Entities.Core.Account", b =>
            {
                b.HasOne("ArtiX.Domain.Entities.Core.Company", "Company")
                    .WithMany()
                    .HasForeignKey("CompanyId")
                    .OnDelete(DeleteBehavior.Cascade)
                    .IsRequired();

                b.Navigation("Company");
            });

            modelBuilder.Entity("ArtiX.Domain.Entities.Core.Branch", b =>
            {
                b.HasOne("ArtiX.Domain.Entities.Core.Company", "Company")
                    .WithMany("Branches")
                    .HasForeignKey("CompanyId")
                    .OnDelete(DeleteBehavior.Cascade)
                    .IsRequired();

                b.Navigation("Company");
            });

            modelBuilder.Entity("ArtiX.Domain.Entities.Core.Customer", b =>
            {
                b.HasOne("ArtiX.Domain.Entities.Core.Branch", "Branch")
                    .WithMany()
                    .HasForeignKey("BranchId")
                    .OnDelete(DeleteBehavior.Restrict);

                b.HasOne("ArtiX.Domain.Entities.Core.Company", "Company")
                    .WithMany()
                    .HasForeignKey("CompanyId")
                    .OnDelete(DeleteBehavior.Cascade)
                    .IsRequired();

                b.HasOne("ArtiX.Domain.Entities.Core.SalesRepresentative", "DefaultSalesRepresentative")
                    .WithMany()
                    .HasForeignKey("DefaultSalesRepresentativeId")
                    .OnDelete(DeleteBehavior.Restrict);

                b.Navigation("Branch");

                b.Navigation("Company");

                b.Navigation("DefaultSalesRepresentative");
            });

            modelBuilder.Entity("ArtiX.Domain.Entities.Core.Product", b =>
            {
                b.HasOne("ArtiX.Domain.Entities.Core.Company", "Company")
                    .WithMany()
                    .HasForeignKey("CompanyId")
                    .OnDelete(DeleteBehavior.Cascade)
                    .IsRequired();

                b.Navigation("Company");
            });

            modelBuilder.Entity("ArtiX.Domain.Entities.Core.SalesChannel", b =>
            {
                b.HasOne("ArtiX.Domain.Entities.Core.Company", "Company")
                    .WithMany("SalesChannels")
                    .HasForeignKey("CompanyId")
                    .OnDelete(DeleteBehavior.Cascade)
                    .IsRequired();

                b.Navigation("Company");
            });

            modelBuilder.Entity("ArtiX.Domain.Entities.Core.SalesRepresentative", b =>
            {
                b.HasOne("ArtiX.Domain.Entities.Core.Company", "Company")
                    .WithMany("SalesRepresentatives")
                    .HasForeignKey("CompanyId")
                    .OnDelete(DeleteBehavior.Cascade)
                    .IsRequired();

                b.Navigation("Company");
            });

            modelBuilder.Entity("ArtiX.Domain.Entities.Core.Warehouse", b =>
            {
                b.HasOne("ArtiX.Domain.Entities.Core.Branch", "Branch")
                    .WithMany()
                    .HasForeignKey("BranchId")
                    .OnDelete(DeleteBehavior.Restrict);

                b.HasOne("ArtiX.Domain.Entities.Core.Company", "Company")
                    .WithMany()
                    .HasForeignKey("CompanyId")
                    .OnDelete(DeleteBehavior.Cascade)
                    .IsRequired();

                b.Navigation("Branch");

                b.Navigation("Company");
            });

            modelBuilder.Entity("ArtiX.Domain.Entities.Sales.DeliveryNote", b =>
            {
                b.HasOne("ArtiX.Domain.Entities.Core.Branch", "Branch")
                    .WithMany()
                    .HasForeignKey("BranchId")
                    .OnDelete(DeleteBehavior.Restrict);

                b.HasOne("ArtiX.Domain.Entities.Core.Company", "Company")
                    .WithMany()
                    .HasForeignKey("CompanyId")
                    .OnDelete(DeleteBehavior.Cascade)
                    .IsRequired();

                b.HasOne("ArtiX.Domain.Entities.Core.SalesChannel", "SalesChannel")
                    .WithMany()
                    .HasForeignKey("SalesChannelId")
                    .OnDelete(DeleteBehavior.Restrict);

                b.HasOne("ArtiX.Domain.Entities.Core.SalesRepresentative", "SalesRepresentative")
                    .WithMany()
                    .HasForeignKey("SalesRepresentativeId")
                    .OnDelete(DeleteBehavior.Restrict);

                b.Navigation("Branch");

                b.Navigation("Company");

                b.Navigation("SalesChannel");

                b.Navigation("SalesRepresentative");
            });

            modelBuilder.Entity("ArtiX.Domain.Entities.Sales.Invoice", b =>
            {
                b.HasOne("ArtiX.Domain.Entities.Core.Branch", "Branch")
                    .WithMany()
                    .HasForeignKey("BranchId")
                    .OnDelete(DeleteBehavior.Restrict);

                b.HasOne("ArtiX.Domain.Entities.Core.Company", "Company")
                    .WithMany()
                    .HasForeignKey("CompanyId")
                    .OnDelete(DeleteBehavior.Cascade)
                    .IsRequired();

                b.HasOne("ArtiX.Domain.Entities.Core.SalesChannel", "SalesChannel")
                    .WithMany()
                    .HasForeignKey("SalesChannelId")
                    .OnDelete(DeleteBehavior.Restrict);

                b.HasOne("ArtiX.Domain.Entities.Core.SalesRepresentative", "SalesRepresentative")
                    .WithMany()
                    .HasForeignKey("SalesRepresentativeId")
                    .OnDelete(DeleteBehavior.Restrict);

                b.Navigation("Branch");

                b.Navigation("Company");

                b.Navigation("SalesChannel");

                b.Navigation("SalesRepresentative");
            });

            modelBuilder.Entity("ArtiX.Domain.Entities.Sales.Payment", b =>
            {
                b.HasOne("ArtiX.Domain.Entities.Core.Branch", "Branch")
                    .WithMany()
                    .HasForeignKey("BranchId")
                    .OnDelete(DeleteBehavior.Restrict);

                b.HasOne("ArtiX.Domain.Entities.Core.Company", "Company")
                    .WithMany()
                    .HasForeignKey("CompanyId")
                    .OnDelete(DeleteBehavior.Cascade)
                    .IsRequired();

                b.HasOne("ArtiX.Domain.Entities.Core.SalesChannel", "SalesChannel")
                    .WithMany()
                    .HasForeignKey("SalesChannelId")
                    .OnDelete(DeleteBehavior.Restrict);

                b.HasOne("ArtiX.Domain.Entities.Core.SalesRepresentative", "SalesRepresentative")
                    .WithMany()
                    .HasForeignKey("SalesRepresentativeId")
                    .OnDelete(DeleteBehavior.Restrict);

                b.Navigation("Branch");

                b.Navigation("Company");

                b.Navigation("SalesChannel");

                b.Navigation("SalesRepresentative");
            });

            modelBuilder.Entity("ArtiX.Domain.Entities.Sales.Quotation", b =>
            {
                b.HasOne("ArtiX.Domain.Entities.Core.Branch", "Branch")
                    .WithMany()
                    .HasForeignKey("BranchId")
                    .OnDelete(DeleteBehavior.Restrict);

                b.HasOne("ArtiX.Domain.Entities.Core.Company", "Company")
                    .WithMany()
                    .HasForeignKey("CompanyId")
                    .OnDelete(DeleteBehavior.Cascade)
                    .IsRequired();

                b.HasOne("ArtiX.Domain.Entities.Core.SalesChannel", "SalesChannel")
                    .WithMany()
                    .HasForeignKey("SalesChannelId")
                    .OnDelete(DeleteBehavior.Restrict);

                b.HasOne("ArtiX.Domain.Entities.Core.SalesRepresentative", "SalesRepresentative")
                    .WithMany()
                    .HasForeignKey("SalesRepresentativeId")
                    .OnDelete(DeleteBehavior.Restrict);

                b.Navigation("Branch");

                b.Navigation("Company");

                b.Navigation("SalesChannel");

                b.Navigation("SalesRepresentative");
            });

            modelBuilder.Entity("ArtiX.Domain.Entities.Sales.SalesOrder", b =>
            {
                b.HasOne("ArtiX.Domain.Entities.Core.Branch", "Branch")
                    .WithMany()
                    .HasForeignKey("BranchId")
                    .OnDelete(DeleteBehavior.Restrict);

                b.HasOne("ArtiX.Domain.Entities.Core.Company", "Company")
                    .WithMany()
                    .HasForeignKey("CompanyId")
                    .OnDelete(DeleteBehavior.Cascade)
                    .IsRequired();

                b.HasOne("ArtiX.Domain.Entities.Core.SalesChannel", "SalesChannel")
                    .WithMany()
                    .HasForeignKey("SalesChannelId")
                    .OnDelete(DeleteBehavior.Restrict);

                b.HasOne("ArtiX.Domain.Entities.Core.SalesRepresentative", "SalesRepresentative")
                    .WithMany()
                    .HasForeignKey("SalesRepresentativeId")
                    .OnDelete(DeleteBehavior.Restrict);

                b.Navigation("Branch");

                b.Navigation("Company");

                b.Navigation("SalesChannel");

                b.Navigation("SalesRepresentative");
            });

            modelBuilder.Entity("ArtiX.Domain.Entities.Sales.SalesOrderLine", b =>
            {
                b.HasOne("ArtiX.Domain.Entities.Core.Product", "Product")
                    .WithMany()
                    .HasForeignKey("ProductId")
                    .OnDelete(DeleteBehavior.Cascade)
                    .IsRequired();

                b.HasOne("ArtiX.Domain.Entities.Sales.SalesOrder", "SalesOrder")
                    .WithMany()
                    .HasForeignKey("SalesOrderId")
                    .OnDelete(DeleteBehavior.Cascade)
                    .IsRequired();

                b.Navigation("Product");

                b.Navigation("SalesOrder");
            });

            modelBuilder.Entity("ArtiX.Domain.Entities.Core.Company", b =>
            {
                b.Navigation("Branches");

                b.Navigation("SalesChannels");

                b.Navigation("SalesRepresentatives");
            });
        }
    }
}
